version: "3.9"
services:
  mysqldb:
    image: mysql:8.0.22
    environment:
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  mongodb:
    image: mongo:5.0.6
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672