apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherdeployment
  labels:
    app: weatherdeployment
spec:
  selector:
    matchLabels:
      app: weatherdeployment
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: weatherdeployment
      labels:
        app: weatherdeployment
    spec:
      containers:
      - name: weathercontainer
        image: rsotosan/weatherservice:1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topodeployment
  labels:
    app: topodeployment
spec:
  selector:
    matchLabels:
      app: topodeployment
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: topodeployment
      labels:
        app: topodeployment
    spec:
      containers:
      - name: topocontainer
        image: rsotosan/toposervice:1.0
        env:
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plannerdeployment
  labels:
    app: plannerdeployment
spec:
  selector:
    matchLabels:
      app: plannerdeployment
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: plannerdeployment
      labels:
        app: plannerdeployment
    spec:
      containers:
      - name: plannercontainer
        image: rsotosan/eoloplanner:1.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: TOPO_HOST
          value: "toposervice"
        - name: TOPO_PORT
          value: "8080"  
        - name: WEATHER_HOST
          value: "weatherservice"
        - name: WEATHER_PORT
          value: "9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverdeployment
  labels:
    app: serverdeployment
spec:
  selector:
    matchLabels:
      app: serverdeployment
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: serverdeployment
      labels:
        app: serverdeployment
    spec:
      containers:
      - name: servercontainer
        image: rsotosan/server:1.0
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherservice
spec:
  ports:
  - port: 9090
  selector:
    app: weatherdeployment
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
spec:
  ports:
  - port: 8080
  selector:
    app: topodeployment
  type: ClusterIP
---
kind: Service 
apiVersion: v1 
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app: serverdeployment 
  ports:
    - nodePort: 30000
      port: 3000 
      targetPort: 3000