// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WeatherService.proto

package es.grpc;

public interface GetWeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:es.grpc.GetWeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
