// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/WeatherService.proto

package es.grpc;

public final class WeatherServiceOuterClass {
  private WeatherServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_grpc_GetWeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_grpc_GetWeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_es_grpc_Weather_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_es_grpc_Weather_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/proto/WeatherService.proto\022\007e" +
      "s.grpc\"!\n\021GetWeatherRequest\022\014\n\004city\030\001 \001(" +
      "\t\"(\n\007Weather\022\014\n\004city\030\001 \001(\t\022\017\n\007weather\030\002 " +
      "\001(\t2L\n\016WeatherService\022:\n\nGetWeather\022\032.es" +
      ".grpc.GetWeatherRequest\032\020.es.grpc.Weathe" +
      "rB\013\n\007es.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_es_grpc_GetWeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_es_grpc_GetWeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_grpc_GetWeatherRequest_descriptor,
        new java.lang.String[] { "City", });
    internal_static_es_grpc_Weather_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_es_grpc_Weather_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_es_grpc_Weather_descriptor,
        new java.lang.String[] { "City", "Weather", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
